services:
  db:
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=meari
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=weather_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: