CREATE TABLE users
(
    id       INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login    VARCHAR(255) UNIQUE CHECK ( login >= 3 and login <= 30 ),
    password VARCHAR(255) CHECK ( login >= 3 and login <= 30 ),
    CONSTRAINT pk_users PRIMARY KEY (id)
);