CREATE TABLE locations
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    user_id   INTEGER,
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

ALTER TABLE locations
    ADD CONSTRAINT FK_LOCATIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE locations
    ADD CONSTRAINT unique_latitude_longitude_user UNIQUE (latitude, longitude, user_id);